#!/bin/bash

set -e

if [[ -n "${VECTORPIPE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        SCALA_VERSION="${SCALA_VERSION:-2.11.12}" ./scripts/test
    fi
fi
