#!/bin/bash

set -e

if [[ -n "${VECTORPIPE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Update Scala dependencies and execute tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        echo "Executing Scala test suite"
        docker-compose run --rm sbt "++${SCALA_VERSION:-2.11.12}" test
    fi
fi
