name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']
    tags: [v*]
  # release:
    # types: [published]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: ["2.12.7"]
    runs-on: ubuntu-latest

    env:
      SCALA_VERSION:  ${{ matrix.scala }}
      BUILD_NUMBER:   ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6
      # - uses: olafurpg/setup-scala@v13
        # with:
          # java-version: adopt@1.8

      - name: run tests
        run: docker compose -f .github/docker-compose.yml up test --abort-on-container-exit --exit-code-from test
